import pandas as pd

df = pd.read_csv(r'c:\Users\a\OneDrive\Desktop\Housing project\indian_housing\data\raw\india_housing_prices.csv')

print('Shape:', df.shape)
print()
print('Columns:', df.columns.tolist())
print()
print('Dtypes:')
print(df.dtypes)
print()
print('Missing values:')
print(df.isnull().sum())
print()
print('Property_Type:', df['Property_Type'].unique())
print()
print('Furnished_Status:', df['Furnished_Status'].unique())
print()
print('City:', df['City'].unique())
print()
print('State:', df['State'].unique())
print()
print('Public_Transport_Accessibility:', df['Public_Transport_Accessibility'].unique())
print()
print('Parking_Space:', df['Parking_Space'].unique())
print()
print('Security:', df['Security'].unique())
print()
print('Facing:', df['Facing'].unique())
print()
print('Owner_Type:', df['Owner_Type'].unique())
print()
print('Availability_Status:', df['Availability_Status'].unique())
print()
print('Locality count:', df['Locality'].nunique())
print()
print('Amenities sample:')
for a in df['Amenities'].head(20):
    print(repr(a))
print()
print('Price_in_Lakhs stats:')
print(df['Price_in_Lakhs'].describe())
print()
print('Size_in_SqFt stats:')
print(df['Size_in_SqFt'].describe())
print()
print('BHK values:', df['BHK'].unique())
print()
print('Age_of_Property stats:')
print(df['Age_of_Property'].describe())
print()
print('Floor_No stats:')
print(df['Floor_No'].describe())
print()
print('Total_Floors stats:')
print(df['Total_Floors'].describe())
print()
print('Nearby_Schools stats:')
print(df['Nearby_Schools'].describe())
print()
print('Nearby_Hospitals stats:')
print(df['Nearby_Hospitals'].describe())
print()
print('Year_Built stats:')
print(df['Year_Built'].describe())
print()
print('Price_per_SqFt stats:')
print(df['Price_per_SqFt'].describe())
print()
print('Head:')
print(df.head(3).to_string())
